version: '3'

services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8741:8741

  config-service:
    build: config-service/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-apigateway:
    build: zuul-apigateway/
    depends_on:
      - config-service
      - eureka-server
      - restaurant-service
      - user-service
    restart: always
    network_mode: "host"

    hostname: localhost
    ports:
      - 8080:8080

  restaurant-service:
    build: restaurant-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8090:8090
    depends_on:
      - config-service
      - eureka-server



  user-service:
    build: user-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8091:8091
    depends_on:
      - config-service
      - eureka-server
